###GET
GET http://localhost:8000/api/books


###POST
POST http://localhost:8000/auth/login
Content-Type: application/json

{ "email":"admin@books.test", "password":"password" }


###POST
POST http://localhost:8000/auth/login
Content-Type: application/json

{ "email":"member@books.test", "password":"password"}


###POST
POST http://localhost:8000/api/books
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJib29rcy1hcGkiLCJzdWIiOjIsImlhdCI6MTc4MjE1MDM0MCwiZXhwIjoxNzgyMTUzOTQwLCJyb2xlIjoibWVtYmVyIiwiZW1haWwiOiJtZW1iZXJAYm9va3MudGVzdCJ9.EjmS5afalUm2_NqCN9odHr7KwdfP5ctWMuuso0tEcHw

{ "title":"Future Book", "author":"X", "year":"2017", "genre":"Fiction"}


###POST
PUT http://localhost:8000/api/books/1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJib29rcy1hcGkiLCJzdWIiOjIsImlhdCI6MTc4MjE1MTQ3MywiZXhwIjoxNzgyMTU1MDczLCJyb2xlIjoibWVtYmVyIiwiZW1haWwiOiJtZW1iZXJAYm9va3MudGVzdCJ9.awDtVG1ZZRermWSi7ngLZwGCxSmkuTXsqBmzQYpTFno

{ 
  "title": "Hijacked"
}

###GET
GET http://localhost:8000/api/books